### ISSUE TITLE
Install from seed failing

### ISSUE THREAD

**Issue by andrechalom** [opendatabio/data#2]
Check https://github.com/opendatabio/opendatabio/issues/187

**Comment by birutaibm** [comment]
Summarizing: The problem is that some versions of mySQL does not work with `geometrycollection` data type for geom field at locations table, so ODB changes this field to `geometry` data type, but the script `LocationSeed_Brazil_2018-03-12` drops this table and create it again with the previous structure.

We need carefully think about this initial step, because similar modifications of ODB in the future may cause the same issue. The table needs to be created only once (or by ODB installation, or by seed process).

**Comment by andrechalom** [comment]
You're right. Working on a new Seed file that does not drop and recreate the table. However, it will need to add the World object, so I'll add a `DELETE locations;` anyway.

**Comment by andrechalom** [comment]
Created a new seed file with the following differences:
- Add the World object (relates to https://github.com/opendatabio/opendatabio/issues/190)
- Removes spurious point / plot samples (see #1)
- Removes the DROP TABLE / CREATE TABLE commands. This way, the column definitions, index, etc will be created respecting the migrations
- Add a "DELETE" command to make sure the table is empty before importing (avoids duplication).

Table structure before dump:
> CREATE TABLE `locations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(191) NOT NULL,
  `parent_id` int(10) unsigned DEFAULT NULL,
  `lft` int(10) unsigned NOT NULL DEFAULT '0',
  `rgt` int(10) unsigned NOT NULL DEFAULT '0',
  `depth` int(11) DEFAULT NULL,
  `altitude` int(11) DEFAULT NULL,
  `adm_level` int(11) NOT NULL,
  `datum` varchar(191) DEFAULT NULL,
  `uc_id` int(10) unsigned DEFAULT NULL,
  `notes` text,
  `x` decimal(8,2) DEFAULT NULL,
  `y` decimal(8,2) DEFAULT NULL,
  `startx` decimal(8,2) DEFAULT NULL,
  `starty` decimal(8,2) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `geom` geometry DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `locations_name_parent_id_unique` (`name`,`parent_id`),
  KEY `locations_uc_id_foreign` (`uc_id`),
  KEY `locations_parent_id_foreign` (`parent_id`),
  CONSTRAINT `locations_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `locations` (`id`),
  CONSTRAINT `locations_uc_id_foreign` FOREIGN KEY (`uc_id`) REFERENCES `locations` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6841 DEFAULT CHARSET=utf8mb4

> select count(1) from locations where name = 'World';
+----------+
| count(1) |
+----------+
|        1 |
+----------+
1 row in set (0.00 sec)

> select count(1) from locations where adm_level > 99;
+----------+
| count(1) |
+----------+
|        0 |
+----------+
1 row in set (0.01 sec)

**Comment by andrechalom** [comment]
Regarding the differences on table structure that may be done in the future, the idea behind having a `seeds.json` to control which data file should be used in each ODB version is exactly to allow us to have different files to serve for versions that make structural changes.
